2018-12-17 21:58:23.555 [error] <0.433.0>@Elixir.PusherWeb.DeliveryChannel:join:4 CRASH REPORT Process <0.433.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PusherWeb.DeliveryChannel':join(<<"deliveries">>, #{<<"token">> => <<"nothing">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.PusherWeb.DeliveryChannel',...}) line 4
2018-12-17 21:58:25.529 [error] <0.434.0>@Elixir.PusherWeb.DeliveryChannel:join:4 CRASH REPORT Process <0.434.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PusherWeb.DeliveryChannel':join(<<"deliveries">>, #{<<"token">> => <<"nothing">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.PusherWeb.DeliveryChannel',...}) line 4
2018-12-17 21:58:30.530 [error] <0.435.0>@Elixir.PusherWeb.DeliveryChannel:join:4 CRASH REPORT Process <0.435.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.PusherWeb.DeliveryChannel':join(<<"deliveries">>, #{<<"token">> => <<"nothing">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.PusherWeb.DeliveryChannel',...}) line 4
2018-12-17 21:59:40.006 [error] <0.412.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Hat">>,<<"created_at">> => <<"2018-12-17T20:59:39.996Z">>,<<"delivery_id">> => nil,<<"id">> => 203,<<"location">> => <<"Storage">>,<<"quantity">> => <<"5">>,<<"updated_at">> => <<"2018-12-17T20:59:39.996Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:40.009 [error] <0.412.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Hat">>,<<"created_at">> => <<"2018-12-17T20:59:39.996Z">>,<<"delivery_id">> => nil,<<"id">> => 203,<<"location">> => <<"Storage">>,<<"quantity">> => <<"5">>,<<"updated_at">> => <<"2018-12-17T20:59:39.996Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:40.009 [error] <0.289.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.412.0> exit with reason {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Hat">>,<<"created_at">> => <<"2018-12-17T20:59:39.996Z">>,<<"delivery_id">> => nil,<<"id">> => 203,<<"location">> => <<"Storage">>,<<"quantity">> => <<"5">>,<<"updated_at">> => <<"2018-12-17T20:59:39.996Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56 in context child_terminated
2018-12-17 21:59:41.251 [error] <0.462.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Chair">>,<<"created_at">> => <<"2018-12-17T20:59:41.235Z">>,<<"delivery_id">> => nil,<<"id">> => 204,<<"location">> => <<"Office">>,<<"quantity">> => <<"2">>,<<"updated_at">> => <<"2018-12-17T20:59:41.235Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:41.253 [error] <0.462.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Chair">>,<<"created_at">> => <<"2018-12-17T20:59:41.235Z">>,<<"delivery_id">> => nil,<<"id">> => 204,<<"location">> => <<"Office">>,<<"quantity">> => <<"2">>,<<"updated_at">> => <<"2018-12-17T20:59:41.235Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:41.253 [error] <0.289.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.462.0> exit with reason {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Chair">>,<<"created_at">> => <<"2018-12-17T20:59:41.235Z">>,<<"delivery_id">> => nil,<<"id">> => 204,<<"location">> => <<"Office">>,<<"quantity">> => <<"2">>,<<"updated_at">> => <<"2018-12-17T20:59:41.235Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56 in context child_terminated
2018-12-17 21:59:41.634 [error] <0.477.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T20:59:41.619Z">>,<<"delivery_id">> => nil,<<"id">> => 205,<<"location">> => <<"Office">>,<<"quantity">> => <<"10">>,<<"updated_at">> => <<"2018-12-17T20:59:41.619Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:41.637 [error] <0.477.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T20:59:41.619Z">>,<<"delivery_id">> => nil,<<"id">> => 205,<<"location">> => <<"Office">>,<<"quantity">> => <<"10">>,<<"updated_at">> => <<"2018-12-17T20:59:41.619Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:41.638 [error] <0.289.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.477.0> exit with reason {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T20:59:41.619Z">>,<<"delivery_id">> => nil,<<"id">> => 205,<<"location">> => <<"Office">>,<<"quantity">> => <<"10">>,<<"updated_at">> => <<"2018-12-17T20:59:41.619Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56 in context child_terminated
2018-12-17 21:59:53.356 [error] <0.492.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T20:59:53.340Z">>,<<"delivery_id">> => nil,<<"id">> => 206,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T20:59:53.340Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:53.359 [error] <0.492.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T20:59:53.340Z">>,<<"delivery_id">> => nil,<<"id">> => 206,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T20:59:53.340Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56
2018-12-17 21:59:53.359 [error] <0.289.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.492.0> exit with reason {badkey,id,#{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T20:59:53.340Z">>,<<"delivery_id">> => nil,<<"id">> => 206,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T20:59:53.340Z">>}} in 'Elixir.Pusher.Subscriber':handle_info/2 line 56 in context child_terminated
2018-12-17 22:00:43.651 [error] <0.406.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Chair">>,<<"created_at">> => <<"2018-12-17T21:00:43.628Z">>,<<"delivery_id">> => nil,<<"id">> => 208,<<"location">> => <<"Office">>,<<"quantity">> => <<"2">>,<<"updated_at">> => <<"2018-12-17T21:00:43.628Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:00:43.660 [error] <0.406.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Chair">>,<<"created_at">> => <<"2018-12-17T21:00:43.628Z">>,<<"delivery_id">> => nil,<<"id">> => 208,<<"location">> => <<"Office">>,<<"quantity">> => <<"2">>,<<"updated_at">> => <<"2018-12-17T21:00:43.628Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:00:43.661 [error] <0.283.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.406.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Chair">>,<<"created_at">> => <<"2018-12-17T21:00:43.628Z">>,<<"delivery_id">> => nil,<<"id">> => 208,<<"location">> => <<"Office">>,<<"quantity">> => <<"2">>,<<"updated_at">> => <<"2018-12-17T21:00:43.628Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2018-12-17 22:00:44.423 [error] <0.433.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Hat">>,<<"created_at">> => <<"2018-12-17T21:00:44.407Z">>,<<"delivery_id">> => nil,<<"id">> => 209,<<"location">> => <<"Storage">>,<<"quantity">> => <<"5">>,<<"updated_at">> => <<"2018-12-17T21:00:44.407Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:00:44.427 [error] <0.433.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Hat">>,<<"created_at">> => <<"2018-12-17T21:00:44.407Z">>,<<"delivery_id">> => nil,<<"id">> => 209,<<"location">> => <<"Storage">>,<<"quantity">> => <<"5">>,<<"updated_at">> => <<"2018-12-17T21:00:44.407Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:00:44.428 [error] <0.283.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.433.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Hat">>,<<"created_at">> => <<"2018-12-17T21:00:44.407Z">>,<<"delivery_id">> => nil,<<"id">> => 209,<<"location">> => <<"Storage">>,<<"quantity">> => <<"5">>,<<"updated_at">> => <<"2018-12-17T21:00:44.407Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2018-12-17 22:00:44.886 [error] <0.448.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T21:00:44.867Z">>,<<"delivery_id">> => nil,<<"id">> => 210,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T21:00:44.867Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:00:44.888 [error] <0.448.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T21:00:44.867Z">>,<<"delivery_id">> => nil,<<"id">> => 210,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T21:00:44.867Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:00:44.889 [error] <0.283.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.448.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T21:00:44.867Z">>,<<"delivery_id">> => nil,<<"id">> => 210,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T21:00:44.867Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2018-12-17 22:01:14.506 [error] <0.397.0> gen_server 'Elixir.Pusher.Subscriber' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T21:01:14.485Z">>,<<"delivery_id">> => nil,<<"id">> => 211,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T21:01:14.485Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:01:14.515 [error] <0.397.0> CRASH REPORT Process 'Elixir.Pusher.Subscriber' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T21:01:14.485Z">>,<<"delivery_id">> => nil,<<"id">> => 211,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T21:01:14.485Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2018-12-17 22:01:14.515 [error] <0.274.0> Supervisor 'Elixir.Pusher.Supervisor' had child 'Elixir.Pusher.Subscriber' started with 'Elixir.Pusher.Subscriber':start_link([]) at <0.397.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{<<"ack">> => false,<<"commodity">> => <<"Pen">>,<<"created_at">> => <<"2018-12-17T21:01:14.485Z">>,<<"delivery_id">> => nil,<<"id">> => 211,<<"location">> => <<"Storage">>,<<"quantity">> => <<"8">>,<<"updated_at">> => <<"2018-12-17T21:01:14.485Z">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
